# docker-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres
    container_name: sms_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sms_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Asia/Kathmandu
      PGTZ: Asia/Kathmandu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: sms_platform_postgres_data
